package demo

const (
	CSTFORGE_LV_AD                               = 1   //锻造台升级，看广告减少升级所需时间（单位：秒） 300
	CSTFORGE_LV_AD_CD                            = 2   //广告的cd时间（单位：秒） 7200
	CSTFORGE_LV_DIAMONDS_TIME                    = 3   //锻造台升级，时间区间（单位：秒）
	CSTFORGE_LV_DIAMONDS                         = 4   //锻造台升级，每个区间加速完成的钻石消耗
	CSTFORGE_LV_HELP                             = 5   //锻造台升级可邀请多少个好友帮助加速 10
	CSTFORGE_LV_HELP_PRECENTAGE                  = 6   //每次帮助加速的时间百分比（占总升级时间） 2
	CSTFORGE_LV_ITEM                             = 7   //升级加速道具，使用单个加速时间（单位：秒） 300
	CSTATTRIBUTES_RESISTANCE                     = 8   //6条抗性属性
	CSTATTRIBUTES_BASE                           = 9   //装备基础属性
	CSTRENAME_CONSUME                            = 10  //单次修改昵称消耗(道具：钻石） 100
	CSTRANK_AMOUNT                               = 11  //排行榜显示最大上榜玩家数量 50
	CSTFORGE_INITIAL_QUANTITY                    = 12  //锻造道具秘银的初始数量（道具id：4） 60
	CSTMAX_LEVEL                                 = 13  //角色最大等级 150
	CSTSPRITE_LV_MAX_1                           = 14  //D级（白色）精灵最大等级上限 150
	CSTSPRITE_LV_MAX_2                           = 15  //C级（绿色）精灵最大等级上限 150
	CSTSPRITE_LV_MAX_3                           = 16  //B级（蓝色）精灵最大等级上限 150
	CSTSPRITE_LV_MAX_4                           = 17  //A级（紫色）精灵最大等级上限 150
	CSTSPRITE_LV_MAX_5                           = 18  //S级（橙色）精灵最大等级上限 150
	CSTNORMAL_SPRITE_TIME                        = 21  //普通精灵蛋(id:10)自动获取时间（单位：秒） 14400
	CSTNORMAL_SPRITE_LIMIT                       = 22  //普通精灵蛋储存数量上限 5
	CSTEQUIP_STRENGTHEN_RESTRICT                 = 23  //装备强化失败掉级的限制（已废弃）
	CSTATTRIBUTES_SPRITE_INHERIT                 = 24  //精灵继承基础属性id
	CSTEXCELLENT_SPRIT_CONSUME                   = 25  //绿色精灵蛋(id:11)单个购买消耗（道具：钻石）
	CSTELITE_SPRIT_CONSUME                       = 26  //蓝色精灵蛋(id:12)单个购买消耗
	CSTWORLDBOSS_XFREE_SWEEP                     = 27  //世界boss每日免费扫荡次数 1
	CSTWORLDBOSS_XDIAMONDS_SWEEP                 = 28  //世界boss扫荡钻石消耗数量
	CSTWORLDBOSS_SWEEP_TIMES                     = 29  //世界boss每日扫荡次数上限（不包含免费扫荡次数） 5
	CSTSOLO_ARENA_DURATION                       = 30  //单人竞技场赛季持续时间（周） 1
	CSTSOLO_ARENA_FREE_TICKET                    = 31  //单人竞技场每日免费挑战次数 3
	CSTSOLO_ARENA_TICKET_DIAMONDS                = 32  //单人竞技场门票购买消耗 10
	CSTSOLO_ARENA_FREE_REFRESH                   = 33  //单人竞技场每日免费刷新次数 3
	CSTSOLO_ARENA_REFRESH_DIAMONDS               = 34  //单人竞技场单次刷新挑战列表金币消耗 600
	CSTSOLO_ARENA_ROBOT_SCORE                    = 35  //单人竞技场机器人玩家初始积分 1000
	CSTSOLO_ARENA_SCORE_ATTENUATE                = 36  //单人竞技场每赛季初始积分衰减比例（百分比） 30
	CSTSOLO_ARENA_SETTLEMENT_TIME                = 37  //单人竞技场每日/赛季结算持续时间（单位：秒） 600
	CSTSOLO_ARENA_PLAYER_SCORE                   = 38  //单人竞技场玩家初始积分 1000
	CSTSOLO_ARENA_RANKLIST_TIME                  = 39  //单人竞技场积分排名信息刷新间隔时间（单位：秒） 300
	CSTSOLO_ARENA_TICKET_CEILING                 = 40  //单人竞技场每日门票购买上限 15
	CSTSOLO_ARENA_ROBOT_ATTRI                    = 41  //单人竞技场机器人玩家属性随机区间（千分比）
	CSTSOLO_ARENA_ROBOT_WINGS                    = 42  //单人竞技场机器人玩家初始翅膀（wings表id） 1
	CSTSOLO_ARENA_ROBOT_PROFILE                  = 43  //单人竞技场机器人玩家头像
	CSTCSTSHOPRANDOM                             = 44  //shop商店商品随的数量 9
	CSTCSTSHOPRANDOM_2                           = 45  //shop商店中广告商品随的数量 3
	CSTARTIFACTSUMMONCONSUME1                    = 46  //神器普通召唤消耗-广告（每日可观看广告次数上限） 1
	CSTARTIFACTSUMMONCONSUME2                    = 47  //神器高级召唤消耗[道具id,道具数量]
	CSTARTIFACTRETURNRATIO                       = 48  //神器返还比例（百分比） 80
	CSTARTIFACTKNAPSACK                          = 49  //神器初始格子以及最大格子数量[初始数量,最大数量]
	CSTARTIFACTSUMMONCONSUME3                    = 50  //神器免费刷新时间（秒） 86400
	CSTARTIFACTMAXINCOME                         = 51  //神器挂机最大收益 3000
	CSTARTIFACTTIME                              = 52  //神器收益时间（秒） 3600
	CSTARTIFACTUNLOCK                            = 53  //神器槽位解锁消耗[第一个,第二个...],超过数组上限则读取最后一个
	CSTARTIFACTPLACEMENTQUANTITY                 = 54  //神器放置数量 5
	CSTARTIFACTSUMMONCONSUME4                    = 55  //神器每次召唤数量 3
	CSTARTIFACTRETURNRATIOITEM                   = 56  //神器返还道具id（已废弃） 21
	CSTGUILD_BONFIRE_COST                        = 57  //公会建设，选择消耗钻石点燃时，需要花费的钻石数量 50
	CSTGUILD_CREATE_COST                         = 58  //创建公会需要花费的钻石数量 200
	CSTGUILD_BOSS_TIMES_FREE                     = 59  //公会BOSS挑战次数（每日） 1
	CSTGUILD_LETTER                              = 60  //公会名称和公告的最多字数（以英文字符为基准）
	CSTGUILD_CHANGE_NAME_COST                    = 61  //公会改名需要花费的钻石数量 100
	CSTGUILD_SETTLEMENT_TIME                     = 62  //公会联赛结算持续时间（单位：秒） 300
	CSTGUILD_LETTER_MIN                          = 63  //公会名称最少字数（以英文字符为基准） 3
	CSTGUILD_TASK_NUM                            = 64  //公会联赛任务池任务数量 9
	CSTGUILD_TASK_REFRESH                        = 65  //公会联赛任务刷新倒计时（单位：秒） 300
	CSTGUILD_TASK_TIMES                          = 66  //公会联赛个人可接取任务数量 5
	CSTGUILD_CHAT_FORGELIST_LIMIT                = 67  //公会聊天-锻造台升级加速帮助-帮助列表数量上限 20
	CSTTOWER1                                    = 68  //排行榜显示玩家上限 50
	CSTACTIVITY_GRUADS_DAILY_TIMES               = 69  //矿脉攻略战活动每日挑战次数 5
	CSTACTIVITY_GRUADS_STAGE_PLAYER              = 70  //矿脉攻略战活动关卡有X个玩家通关后，可进入下一关 3
	CSTARTIFACTFIRST                             = 71  //玩家达到30级，开启神器功能后，默认拥有的神器id，读取ArtifactReward.xlsx 100
	CSTGUILD_CHAT_HELP_NUM                       = 72  //公会聊天-锻造台升级加速帮助-帮助玩家数量上限 10
	CSTGUILD_CHAT_HELP_CD                        = 73  //公会聊天-锻造台升级加速帮助-分享帮助cd（单位：秒） 1800
	CSTACTIVITY_SECRETSTONE_REFINE_ROUNDS        = 74  //炼造大师每次活动轮数 3
	CSTSECRETSTONE_GROOVE_FUNCTION               = 75  //秘石三个槽位的开启等级（角色等级）
	CSTSECRETSTONE_ATTRIBUTES                    = 76  //秘石基础属性id
	CSTGUILD_TASK_LIMIT_POINT                    = 77  //公会联赛个人可领奖保底积分 90
	CSTSECRETSTONESTAR_ATTRIBUTES                = 78  //秘石星星累计达标，属性id
	CSTSECRETSTONE_FREE_TIME                     = 79  //每X秒，秘石可以免费炼造 86400
	CSTSECRETSTONE_FREE_TIMES                    = 80  //秘石免费炼造次数 5
	CSTRATEPOP_LEVEL                             = 81  //玩家达到X及时，弹出好评引导弹窗 9
	CSTTITLE_FIRST_GET                           = 82  //玩家默认拥有的首个称号，读取titleMain 1
	CSTACTIVITY_SPIRIT_SYNTHESIS_ROUNDS          = 83  //合成大作战每次活动轮数 5
	CSTACTIVITY_SPIRIT_SYNTHESIS_POINT           = 84  //合成精灵品质对应积分，数组分别对应：白、绿、蓝、紫、橙、金、红
	CSTACTIVITY_SMITHINGMASTER_ROUNDS            = 85  //锻造大师活动 每次活动轮数 3
	CSTAVATAR_FIRST                              = 86  //玩家默认拥有的头像id，读取AvatarResource.xlsx 1
	CSTAVATAR_UNLOCK                             = 87  //更换头像功能开启的玩家等级（废弃，用FunctionOpen.xslx） 3
	CSTSTAGE_EASY_CHALLENGE_FUNCTION             = 88  //下一关、再次挑战按钮的开启关卡（MainLevel.xlsx的ID） 3001
	CSTSCARLET_SEAL_FLOOR1                       = 89  //封印银柱出现层数part1
	CSTSCARLET_SEAL_FLOOR1_WEIGHTS1              = 90  //对应每层权重part1
	CSTSCARLET_SEAL_FLOOR2                       = 91  //封印银柱出现层数part2
	CSTSCARLET_SEAL_FLOOR1_WEIGHTS2              = 92  //对应每层权重part1
	CSTSCARLET_PLACE_CHEST_SLOT                  = 93  //放置宝箱需要解锁的槽位（第几个槽位需要解锁 3
	CSTSCARLET_CHEST_SLOT_UNLOCK                 = 94  //放置宝箱解锁槽位价格[道具id,道具数量]
	CSTSCARLET_FLOOR_MAX                         = 95  //猩红回廊最大层数 10
	CSTSCARLET_CHEST1_TIME                       = 96  //地宫宝箱开启耗时[道具1id，耗时时长(s)，道具2id，耗时时长(s),...]
	CSTSCARLET_SHOP_POPUP                        = 97  //地宫事件商店内出售道具数量 3
	CSTSCARLET_ATTRIBUTES1                       = 99  //主角历史最高属性记录
	CSTSCARLET_ATTRIBUTES2                       = 100 //主角历史最高属性记录（其中最高值）
	CSTACTIVITY_SMITHINGMASTER_FREEPACKAGE       = 101 //建造达标活动免费礼包id 9001
	CSTSCARLET_ATTRIBUTES3                       = 102 //主角历史最高属性记录（随机打乱分配）
	CSTGEMMINING_COST                            = 103 //寻宝-每次寻宝需要消耗X个灯油 1
	CSTGEMMINING_MAX                             = 104 //寻宝-灯油自动回复数量上限（玩家初始拥有的灯油数量） 150
	CSTGEMMINING_RECOVERY                        = 105 //寻宝-每X秒，回复X个灯油
	CSTGEMMINING_BOUNTY_TASK                     = 106 //寻宝-每日悬赏任务数量 5
	CSTCONDITION1                                = 107 //自动锻造属性筛选 选择框1
	CSTCONDITION2                                = 108 //自动锻造属性筛选 选择框2
	CSTCONDITION3                                = 109 //自动锻造属性筛选 选择框3
	CSTCONDITION4                                = 110 //自动锻造属性筛选 选择框4
	CSTFORGE_CONSUME                             = 111 //自动锻造可选单次锻造消耗数量
	CSTEQUIPMENT_ENHANCE_PRESERVE                = 112 //装备强化使用保级道具等级限制 10
	CSTGEMMINING_TOOL_CLEANSE_COST               = 113 //寻宝工具洗炼消耗的钻石数量 50
	CSTGEMMINING_TOOL_CLEANSE_NUM                = 114 //寻宝工具洗炼出的属性数量（1~3条），对应权重
	CSTACTIVITY_EQUIP_ENHANCEMENT_ROUNDS         = 115 //强化大师每次活动轮数 3
	CSTARTIFACTSKILL_REFRESH_COST                = 116 //刷新神器技能槽位消耗的钻石数量 500
	CSTARTIFACTREFINE_COST                       = 117 //精炼神奇消耗精炼星辰的个数 1
	CSTMONTHLY_CARD_PRIVILEGE1                   = 118 //月卡特权1：出售装备时获得的角色经验+X（月卡到期后不再生效） 2
	CSTETERNAL_CARD_PRIVILEGE1                   = 119 //永恒卡特权1：藏宝阁收益上限+X 2000
	CSTARTIFACTREFINE_LV                         = 120 //神器精炼品质限制（红色，品质为7） 7
	CSTARTIFACTREFINE_LVRESOURCE                 = 121 //神器精炼消耗材料最低等级（蓝色及以上）
	CSTACTIVITY_TREASUREBAG_BIGREWARD            = 122 //百宝袋活动大奖，是ActivityTreasureBag.xlsx表中的第几个奖励 7
	CSTACTIVITY_TREASUREBAG_ROUNDS               = 123 //百宝袋每次活动重置次数 5
	CSTACTIVITY_TREASUREBAG_COST                 = 124 //百宝袋活动每次抽奖消耗的百宝点数数量 10
	CSTARTIFACTSKILL_UNLOCK                      = 125 //神器升阶技能槽位解锁等级
	CSTARTIFACTSKILL_SLOT_LV                     = 126 //神器升阶技能槽位等级上限
	CSTACTIVITY_TREASUREBAG_GO                   = 127 //百宝袋活动，百宝点数获取途径（配置Activity.xlsx活动类型） 20
	CSTACTIVITY_TROVEHUNT_ROUNDS                 = 128 //寻宝达标每次活动轮数 3
	CSTACTIVITY_BOSSINVASION_FREETIMES           = 129 //【已废弃】恶魔入侵活动每日免费挑战次数 1
	CSTBATTLETOKEN_VICTORYSCORE                  = 130 //单人竞技场单次挑战胜利竞技令积分累积 2
	CSTBATTLETOKEN_LOSESCORE                     = 131 //单人竞技场单次失败胜利竞技令积分累积 1
	CSTACTIVITY_BOSSINVASION_COST                = 132 //【已废弃】恶魔入侵活动挑战价格（按购买次数递增，无限购，超出按最后一位价格）
	CSTACTIVITY_TROVE_HUNT                       = 133 //寻宝达标活动免费礼包id 40001
	CSTFORGE_EXTRA_ITEM_DROP                     = 134 //锻造额外产出竞技场挑战券概率[道具id，权重]（千分比）
	CSTFORGE_EXTRA_ITEM_LIMIT                    = 135 //锻造每日额外产出竞技场挑战券上限 5
	CSTACTIVITY_SUPREME_OFFERING_DAY             = 136 //至尊签到开启天数条件（累计登录） 7
	CSTACTIVITY_BOSSINVASION_TIMES               = 137 //恶魔入侵活动每日挑战次数 5
	CSTFORGE_EXTRA_ITEM_SHOW_TIME                = 138 //锻造每日额外产出竞技场挑战券弹窗停留时间（单位：秒） 3
	CSTEQUIP_STRENGTHEN_ADD                      = 139 //单个矮人工艺书道具可提供成功率（千分比） 50
	CSTEQUIP_STRENGTHEN_NUM_LIM                  = 140 //单次强化可使用矮人工艺书数量上限 1
	CSTACTIVITY_GAMEMEMORY_TIMES                 = 141 //暗月马戏团记忆大师活动挑战次数上限 3
	CSTACTIVITY_GAMEMEMORY_ADDTIMES              = 142 //暗月马戏团记忆大师活动挑战次数，每X秒，回复X次
	CSTACTIVITY_GAMEMEMORY_QUANTITY              = 143 //暗月马戏团记忆大师活动每关的牌数（按关卡递增，超出按最后一个数量）
	CSTACTIVITY_GAMEMEMORY_SCORE                 = 144 //暗月马戏团记忆大师活动每消除两张牌的分数 30
	CSTACTIVITY_GAMEMEMORY_CHALLENGE_COUNTDOWN   = 145 //暗月马戏团记忆大师活动每次挑战时间（单位：秒） 90
	CSTACTIVITY_GAMEMEMORY_SHOW_COUNTDOWN        = 146 //暗月马戏团记忆大师活动展示牌面时间，改动的话特效也要调整（单位：秒） 3
	CSTACTIVITY_GAMEMEMORY_SHOW_COUNTDOWN_TIMES  = 147 //暗月马戏团记忆大师活动每日免费挑战次数 0
	CSTTOPARENAMAXSEVER                          = 148 //赛区最多服务器数量：10个 10
	CSTTOPARENASEVERCREATTIME                    = 149 //赛区服务器最大间隔时长：10天 10
	CSTTOPARENAMINPLAYER                         = 150 //小组赛最少参赛人数 64
	CSTTOPARENAREFRESHCOST                       = 151 //花费钻石刷新推荐列表：10 10
	CSTTOPARENABATTLETIMES                       = 152 //选拔赛挑战次数：10 10
	CSTTOPARENABATTLEMAXROUND                    = 153 //选拔赛战斗最大回合数 20
	CSTTOPARENABATTLERECORD                      = 154 //选拔赛最大战斗记录：10 10
	CSTTOPARENABATTLESCORE                       = 155 //选拔赛初始积分：1000 1000
	CSTTOPARENABATTLEPLAYER                      = 156 //选拔赛筛选玩家：64 64
	CSTTOPARENABATTLETEAM                        = 157 //每组玩家数目：8 8
	CSTTOPARENABETSUCCESS                        = 158 //竞猜成功返还倍率 2
	CSTACTIVITY_GAMEEAGLEEYE_TIMES               = 159 //暗月马戏团火眼金睛活动挑战次数上限 3
	CSTACTIVITY_GAMEEAGLEEYE_ADDTIMES            = 160 //暗月马戏团火眼金睛活动挑战次数，每X秒，回复X次
	CSTACTIVITY_GAMEEAGLEEYE_QUANTITY            = 161 //暗月马戏团火眼金睛活动每关的格子数（按关卡递增，超出按最后一个数量）
	CSTACTIVITY_GAMEEAGLEEYE_GOAL1               = 162 //暗月马戏团火眼金睛活动第1关的目标种类 2
	CSTACTIVITY_GAMEEAGLEEYE_GOALNUM1            = 163 //暗月马戏团火眼金睛活动第1关的每种目标的数量 2
	CSTACTIVITY_GAMEEAGLEEYE_GOAL2               = 164 //暗月马戏团火眼金睛活动2~﹢∞关的目标种类（配置的数字区间内随机）
	CSTACTIVITY_GAMEEAGLEEYE_GOALNUM2            = 165 //暗月马戏团火眼金睛活动2~﹢∞关的每种目标的数量（配置的数字区间内随机）
	CSTACTIVITY_GAMEEAGLEEYE_SCORE               = 166 //暗月马戏团火眼金睛活动每找到1个目标可获得的分数 10
	CSTACTIVITY_GAMEEAGLEEYE_CHALLENGE_COUNTDOWN = 167 //暗月马戏团火眼金睛活动每次挑战时间（单位：秒） 90
	CSTACTIVITY_GAMEEAGLEEYE_SCORE_WRONG         = 168 //暗月马戏团火眼金睛活动每点错1个目标要减去的分数 10
	CSTGEMORB_FREE_TIME                          = 169 //每X秒，宝珠可以免费净化（废弃，每日0点刷新免费次数） 86400
	CSTGEMORB_FREE_TIMES                         = 170 //宝珠免费净化次数 1
	CSTGEMORB_SUMMON_ENERGE_EVERYTIME            = 171 //每次进行宝珠净化可获得的能量 1
	CSTGEMORB_SUMMON_ENERGE_FULL                 = 172 //宝珠能量到达X时可领奖 500
	CSTGEMORB_SUMMON_ENERGE_ORBID                = 173 //宝珠能量奖励ID（GemOrb.xlsx）
	CSTGEMORB_SUMMON_ENERGE_ORBIDWEIGHT          = 174 //宝珠能量奖励权重（和ID一一对应）
	CSTGEMORB_FUNCTION                           = 175 //宝珠功能在宝石藏馆X级时开启 3
	CSTACTIVITY_MASTERCONTEST_ROUNDS             = 176 //大师争霸赛每次活动轮数 5
	CSTSPRITE_MANOR_ITEM                         = 177 //家园中精灵蛋对应道具[第一个蛋id，第二个蛋id，第三个蛋id]
	CSTGUILD_FIGHT_CONSUM                        = 178 //公会乱斗-每次匹配消耗次数 1
	CSTGUILD_FIGHT_FREE                          = 179 //公会乱斗-每日免费次数 3
	CSTGUILD_FIGHT_ADD                           = 180 //公会乱斗-每X秒，回复X次挑战次数
	CSTGUILD_FIGHT_ITEM                          = 181 //公会乱斗-匹配次数购买消耗[道具id] 3
	CSTGUILD_FIGHT_PRICES                        = 182 //公会乱斗-匹配次数购买消耗[第一次消耗，第二次消耗...]超过最大值都读取最大值
	CSTGULID_RANK_NUM                            = 183 //公会乱斗-排行榜显示数量 50
	CSTGULID_RANK_SIGNUP_LIMIT                   = 184 //公会乱斗-报名条件人数限制 10
	CSTGULID_FIGHT_START_DAY                     = 185 //公会乱斗-赛区开启第X天可开启玩法 8
	CSTGUILD_FIGHT_SETTLEMENT_TIME               = 186 //公会乱斗-结算持续时间（单位：秒） 300
	CSTACTIVITY_SHIPWRECK_NUM                    = 187 //沉船每层宝藏格子数量（仅后端用，有改动要修改美术界面） 30
	CSTACTIVITY_SHADOW_POWER_MAX                 = 188 //魔影地牢-体力上限（每日活动探索时间开始，可获得的体力） 30
	CSTACTIVITY_SHADOW_POWER_ADD_TIMES           = 189 //魔影地牢-体力每X秒恢复1点 600
	CSTACTIVITY_SHADOW_POWER_ADD_ITEM            = 190 //魔影地牢-1个体力回复道具（item58）可增加X点体力 5
	CSTACTIVITY_SHADOW_EXPLORE_POWER_COST        = 191 //魔影地牢-每层每次探索消耗体力 [第一层，第二层，第三层]
	CSTACTIVITY_SHADOW_THIRDFLOOR_ENERGY_GET     = 192 //魔影地牢-玩家每次进入第三层，可获得X点精力 20
	CSTACTIVITY_SHADOW_PLAYER_FAIL_COST          = 193 //魔影地牢-狭路相逢事件，每次被人击杀扣除X点精力 1
	CSTACTIVITY_SHADOW_MONSTER_CHALLENGE_CD      = 194 //魔影地牢-挑战怪物事件cd（单位：秒） 7200
	CSTACTIVITY_SHADOW_PLAYER_CHALLENGE_CD       = 195 //魔影地牢-挑战玩家事件cd（单位：秒） 7200
	CSTACTIVITY_SHADOW_EXPLORE_TIME              = 196 //魔影地牢-探索时间（UTC+0），不能跨天
	CSTGUILD_NOTICE_LIMIT                        = 197 //公会乱斗-播报储存记录数量条目限制 50
	CSTGUILD_NOTICE_CONDITION                    = 198 //公会乱斗-触发播报的击杀人数条件 10
	CSTACTIVITY_SHADOW_BUFF_SHOW                 = 199 //魔影地牢-护符界面上方显示的属性加成条目(AttributesLanguage.xlsx 的ID)
	CSTARTIFACT_SUMMON_ENERGE_EVERYTIME          = 200 //每次进行神器高级刷新可获得的能量 1
	CSTARTIFACT_SUMMON_ENERGE_FULL               = 201 //神器高级刷新能量到达X时可领奖 100
	CSTARTIFACT_SUMMON_ENERGE_ORBID              = 202 //神器高级刷新能量奖励ID（ArtifactReward.xlsx）
	CSTARTIFACT_SUMMON_ENERGE_ORBIDWEIGHT        = 203 //神器高级刷新能量奖励权重（和ID一一对应）
)
